// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SuccessController from "./success_controller"
application.register("success", SuccessController)

import SurveyController from "./survey_controller"
application.register("survey", SurveyController)
